Feature/JSSNMSHDD-3279 query RelationshipAttributes by many third parties
nmshd/cns-runtime pull request #131
Opened 2022-11-16 14:07 UTC by jkoenig134

2022-11-16 15:22 UTC, tnotheis requested changes

2022-11-16 15:22 UTC, tnotheis commented on src/dataViews/DataViewExpander.ts
> -            valueType: correctlyTypedAttribute.valueType,
Warum wurde hier so viel gelöscht?

2022-11-16 15:22 UTC, tnotheis commented on src/useCases/consumption/attributes/ExecuteThirdPartyRelationshipAttributeQuery.ts
> +        return Result.ok(AttributeMapper.toAttributeDTOList(attribute));
Find ich besser so 👍

2022-11-17 10:36 UTC, tnotheis requested changes

2022-11-17 11:08 UTC, jkoenig134 commented on src/dataViews/DataViewExpander.ts
> -            valueType: correctlyTypedAttribute.valueType,
Du hast doch in den results die ganzen gefundenen Attribute, darauf kann man weiter arbeiten.

2022-11-17 11:17 UTC, jkoenig134 commented on src/dataViews/DataViewExpander.ts
> -            valueType: correctlyTypedAttribute.valueType,
Schau dir als Referenz mal die IdentityAttributeQuery an, da ist es genauso.

2022-11-18 06:59 UTC, tnotheis commented on src/dataViews/DataViewExpander.ts
> -            valueType: correctlyTypedAttribute.valueType,
Joa, das meinte ich ja mit dem zweiten Teil meines Kommentars. Dann war die Implementierung einfach nur seltsam.

@stnmtz Hattest du einen validen rund dafür, renderHints, valueHints und valueType nochmal extra aufzunehmen?

2022-11-21 06:50 UTC, tnotheis approved these changes
Ich approve jetzt einfach mal. Sollte @stnmtz doch noch was dagegen haben, müssen wir es eben rückgängig machen.

2022-11-21 07:23 UTC, tnotheis requested changes
Thomas hat mich in einer Teams-Nachricht darum gebeten, dass wir mit dem Merge noch warten.

2022-11-22 07:40 UTC, stnmtz approved these changes

2022-11-22 07:53 UTC, tnotheis approved these changes

2022-11-22 07:56 UTC, merged