Feature/jssnmshdd 3251 add query possibility to hide technical fields
nmshd/cns-runtime pull request #134
Opened 2022-12-01 12:18 UTC by aince42

2022-12-01 12:41 UTC, jkoenig134 requested changes

2022-12-01 12:41 UTC, jkoenig134 commented on src/useCases/consumption/attributes/GetAttributes.ts
> +        if (request.hideTechnical) {
geht das nicht viel schöner (und v.a. auf db-Ebene) über eine custom query?

2022-12-01 12:41 UTC, jkoenig134 commented on src/useCases/consumption/attributes/GetAttributes.ts
> +        if (request.hideTechnical) {
gilt auch für alle anderen Vorkommen.

2022-12-01 12:41 UTC, jkoenig134 commented on test/consumption/attributes.test.ts
> +    test("should hide technical attributes when hideTechnical=true", async () => {
tests für GetAttributesForRelationshipUseCase und GetSharedToPeerAttributesRequestQuery fehlen

2022-12-02 13:48 UTC, tnotheis requested changes

2022-12-05 13:21 UTC, jkoenig134 requested changes

2022-12-05 13:21 UTC, jkoenig134 commented on test/consumption/attributes.test.ts
> +        }
da hatten wir ja eigentlich gesagt, dass es nicht nötig sein sollte, weil über getAttributes schon alles gelöscht wurde.

2022-12-05 13:31 UTC, tnotheis commented on test/consumption/attributes.test.ts
> +        }
@jkoenig134  Aufpassen, bei der zweiten Schleife wird über die Attributes des Recipients iteriert (`recipient.consumption.attributes.getAttributes()`). Bei der ersten über die des Senders (`sender.consumption.attributes.getAttributes()`)

2022-12-05 13:32 UTC, jkoenig134 commented on test/consumption/attributes.test.ts
> +        }
jetzt sehe ich was du dort tust, das naming ist verwirrend.

änder mal bitte in 
- z65 `attributes` -> `senderAttributesResponse`
- z65 `{ query: {} }` -> `{}`
- z69 `peerAttributes` -> `recipientAttributesResponse`

und entferne in z65

2022-12-05 13:32 UTC, tnotheis commented on test/consumption/attributes.test.ts
> +        }
Habe ich auch erst gesehen als ich nach unserem gemeinsamen Call letzte Woche nochmal zusammen mit Ali drauf geschaut habe

2022-12-05 13:42 UTC, jkoenig134 commented on test/consumption/attributes.test.ts
> +        for (const peerAttribute of recipientAttributesResponse.value) {
peerAttribute -> attribute

2022-12-05 13:42 UTC, aince42 commented on test/consumption/attributes.test.ts
> +        }
Ist erledigt

2022-12-05 13:45 UTC, aince42 commented on test/consumption/attributes.test.ts
> +        for (const peerAttribute of recipientAttributesResponse.value) {
Ist erledigt

2022-12-05 13:47 UTC, tnotheis submitted a review, later dismissed
Passt von meiner Seite aus. Warte aber besser noch bis Julian auch approved hat.

2022-12-05 13:51 UTC, jkoenig134 approved these changes

2022-12-05 13:57 UTC, merged