Bugfix/check empty array
nmshd/cns-runtime pull request #169
Opened 2023-09-18 17:05 UTC by stnmtz

2023-09-18 17:09 UTC, jkoenig134 commented on package.json
version bump

2023-09-19 06:09 UTC, tnotheis requested changes

2023-09-19 06:09 UTC, tnotheis commented on src/dataViews/DataViewExpander.ts
> +            valueHints = matchedAttributeDVOs[0].valueHints;
These values aren't used anywhere, as far as I can see.

2023-09-19 06:32 UTC, stnmtz commented on src/dataViews/DataViewExpander.ts
> +            valueHints = matchedAttributeDVOs[0].valueHints;
Schau ins return Statement - da hat sich nur nichts geändert ;)

2023-09-19 06:33 UTC, tnotheis approved these changes

2023-09-19 06:42 UTC, jkoenig134 approved these changes

2023-09-19 07:19 UTC, merged