Fix/fallback for iql query
nmshd/cns-runtime pull request #171
Opened 2023-10-04 13:10 UTC by stnmtz

2023-10-04 18:25 UTC, jkoenig134 commented on package.json
> +    "version": "2.8.1",
2.8.0?

2023-10-04 18:27 UTC, jkoenig134 requested changes

2023-10-04 18:27 UTC, jkoenig134 commented on .ci/runChecks.sh
> +npx better-npm-audit audit --exclude=1094239
this is fixable.

2023-10-05 06:09 UTC, jkoenig134 approved these changes

2023-10-06 06:05 UTC, slavistan approved these changes

2023-10-06 06:05 UTC, merged