Chore/get versions of attribute
nmshd/cns-runtime pull request #182
Opened 2023-12-08 12:12 UTC by Milena-Czierlinski

2023-12-08 16:41 UTC, slavistan commented on src/useCases/consumption/attributes/GetVersionsOfAttribute.ts
> +            throw RuntimeErrors.general.invalidPropertyValue("The given ID doesn't belong to a valid Attribute.");
Nitpicking: The error message may suggest that the given ID then belongs to an _invalid_ attribute instead (it's not definitively clear to an outsider what the problem is). I politely suggest keeping it stupid and simple with `Attribute '${request.attributeId}' doesn't exist.`.

2023-12-08 16:41 UTC, slavistan commented on test/consumption/attributes-e2e.test.ts
> +describe("Get (shared) versions of an identity attribute", () => {
I suggest putting these tests into a dedicated `describe()` block, just as we did with the other use cases in that file. Makes it immediately apparent where which use cases is tested.

2023-12-08 16:41 UTC, slavistan commented on test/consumption/attributes-e2e.test.ts
>      let updatedRepositoryAttributeVersion2: LocalAttributeDTO;
Would love for these two to just be called `repositoryAttributeVersion{1,2}`, without the _updated_ prefix. The _updated_ part is an artifact from the implementation of the successions where we have two different states of the same attribute to maintain. You can hide that detail in the `beforeAll` test setup and not let it escape :-)

Changing the cumbersome name would make all the tests much easier to read. Same goes for the other `updated...` variable names outside of the test setup.

2023-12-11 10:02 UTC, Milena-Czierlinski commented
Mmh, the rebase did weird things and duplicated some commits.

2023-12-11 10:02 UTC, jkoenig134 commented
I think the PR title is a bit confusing..

1. this is no chore, you are actually changing code that is shipped
2. this feels like a bugfix, you are checking stuff that wasn't checked before but should be checked - please make sure to add this to the PR title and to the merge message

2023-12-11 10:03 UTC, jkoenig134 requested changes

2023-12-11 10:03 UTC, jkoenig134 commented on src/useCases/consumption/attributes/GetVersionsOfAttribute.ts
> +        }
record not found

2023-12-11 10:30 UTC, jkoenig134 requested changes

2023-12-11 10:30 UTC, jkoenig134 commented on src/useCases/consumption/attributes/GetSharedVersionsOfIdentityAttribute.ts
> +            throw RuntimeErrors.general.recordNotFound(request.attributeId);
```suggestion
            throw RuntimeErrors.general.recordNotFound(LocalAttribute);
```

2023-12-11 10:30 UTC, jkoenig134 commented on src/useCases/consumption/attributes/GetVersionsOfAttribute.ts
> +            throw RuntimeErrors.general.recordNotFound(request.attributeId);
see above

2023-12-11 10:53 UTC, jkoenig134 approved these changes

2023-12-11 12:43 UTC, Milena-Czierlinski commented
"The merge-base changed after approval." -> Looking this up, it seems I have to close and re-open this PR, in order to work around it.

2023-12-11 12:43 UTC, closed without merging