Feature/jssnmshdd 2839 implement create challenge usecase
nmshd/cns-runtime pull request #37
Opened 2022-02-04 13:57 UTC by jkoenig134

2022-02-04 16:36 UTC, Lea-Zim approved these changes

2022-02-07 06:54 UTC, tnotheis requested changes

2022-02-07 06:54 UTC, tnotheis commented on src/useCases/transport/challenges/CreateChallenge.ts
> +class Validator extends RuntimeValidator<CreateChallengeRequest> {
Schreib den Validator doch gleich mit einem JSON Schema.

2022-02-07 06:54 UTC, tnotheis commented on src/useCases/transport/challenges/CreateChallenge.ts
> +            .withFailureMessage("relationship is required when challengeType is Relationship");
Ich glaube, `relationship`, `challengeType` und `Relationship` sollten jeweils in single Quotes. Sonst hört sich der Satz irgendwie komisch an. :D

2022-02-07 06:54 UTC, tnotheis commented on src/useCases/transport/challenges/CreateChallenge.ts
> +    private async getRelationship(request: CreateChallengeRequest): Promise<Result<Relationship | undefined>> {
Ich weiß gar nicht mehr ob wir uns hier schon entschieden hatten, aber wir hatten auf jeden Fall mal darüber diskutiert, ob Methoden nicht erst unterhalb der Verwendung definiert werden sollten. Ich war damals stark dafür. Ist ja eine der Clean Code Praktiken, die für einen angenehmeren Lesefluss sorgen. Siehe https://www.baeldung.com/cs/clean-code-formatting#vertical-formatting

2022-02-07 06:54 UTC, tnotheis commented on test/core/challenges.test.ts
> +        expectError(response, "relationship is required when challengeType is Relationship", "error.runtime.validation.invalidPropertyValue");
Denk dran den Test anzupassen, wenn du die Fehlermeldung änderst.

2022-02-07 07:21 UTC, jkoenig134 commented on src/useCases/transport/challenges/CreateChallenge.ts
> +    private async getRelationship(request: CreateChallengeRequest): Promise<Result<Relationship | undefined>> {
Ahja, das hatte ich nur mal so runter geschrieben und wollte es noch verschieben

2022-02-07 07:31 UTC, jkoenig134 commented on src/useCases/transport/challenges/CreateChallenge.ts
> +class Validator extends RuntimeValidator<CreateChallengeRequest> {
Wenn du mir sagst wie ich `'relationship' is required when 'challengeType' is 'Relationship'` damit abbilde gerne^^

2022-02-07 07:34 UTC, jkoenig134 commented on src/useCases/transport/challenges/CreateChallenge.ts
> +class Validator extends RuntimeValidator<CreateChallengeRequest> {
`.isIn(Object.keys(ChallengeType))` ist wohl mit dem SchemaValidator auch nur hardcoded möglich

2022-02-07 08:13 UTC, tnotheis approved these changes

2022-02-07 08:15 UTC, merged