Feature/JSSNMSHDD-2948 local database upgrade procedure
nmshd/cns-runtime pull request #48
Opened 2022-05-03 13:33 UTC by jkoenig134

2022-05-03 13:36 UTC, jkoenig134 commented
@slavistan FYI ;)

2022-05-03 14:29 UTC, tnotheis requested changes

2022-05-04 08:13 UTC, tnotheis requested changes

2022-05-04 08:13 UTC, tnotheis commented on src/DatabaseSchemaUpgrader.ts
> +    public static from(value: { id?: string; version: number }): RuntimeDatabaseSchema {
Ich würde `id` gar nicht erst als Parameter annehmen und einfach immer auf `databaseSchema` setzen.

2022-05-04 08:13 UTC, tnotheis commented on src/DatabaseSchemaUpgrader.ts
> +        const collection = await this.accountController.db.getCollection("meta");
`metaCollection`

2022-05-04 08:13 UTC, tnotheis commented on src/DatabaseSchemaUpgrader.ts
> +class RuntimeDatabaseSchema extends Serializable {
Ich finde den Klassennamen nicht so gut. Das impliziert, dass es tatsächlich das Schema ist. Aber es sind ja die Metadaten von dem Schema.

2022-05-04 08:13 UTC, tnotheis commented on src/DatabaseSchemaUpgrader.ts
> +        const schema = RuntimeDatabaseSchema.from(doc);
Auch der Variablenname: du hast die Metadaten des Schemas, nicht das Schema selbst.

2022-05-04 08:13 UTC, tnotheis commented on src/DatabaseSchemaUpgrader.ts
> +    1: noop // eslint-disable-line @typescript-eslint/naming-convention
Ich würde das wahrscheinlich gar nicht in eine benannte Funktion auslagern. Ist ja ein Ausnahmefall, dass nichts gemacht wird. Normalerweise hast du ja nur eine neue Version, wenn es Änderungen gibt (?)

2022-05-04 08:16 UTC, jkoenig134 commented on src/DatabaseSchemaUpgrader.ts
> +    public static from(value: { id?: string; version: number }): RuntimeDatabaseSchema {
Naja, wenn das aus der DB ausgelesene von serval geparsed wird id ja z.b. rein. Wenn ich das auf serval v2 umstelle kann man sowas mitbedenken

2022-05-04 08:18 UTC, jkoenig134 commented on src/DatabaseSchemaUpgrader.ts
> +    1: noop // eslint-disable-line @typescript-eslint/naming-convention
Stimmt

2022-05-04 09:35 UTC, tnotheis approved these changes

2022-05-04 09:45 UTC, merged