Feature/jssnmshdd 2910 use cases for consumption requests
nmshd/cns-runtime pull request #49
Opened 2022-05-05 11:51 UTC by tnotheis

2022-05-05 17:01 UTC, stnmtz requested changes
Blöde Frage: Sollten wir "interne" APIs wie ein ReceivedIncomingRequest als UseCases nach außen exponieren? Meines Erachtens benötigen wir das eigentlich nicht - Frage wäre, ob es für die Module nicht benötigt wird (wobei die doch afaik auch auf die Consumption Controller direkt zugreifen könnten)

2022-05-06 05:40 UTC, tnotheis commented on src/useCases/consumption/requests/CompleteOutgoingRequest.ts
> +    messageId: string;
> Insofern kann man von außen eigentlich nur Requests completen, die über eine Message reingekommen sind.

Genau. 

> Ggf. sollten wir das Naming vom UseCase von CreateOutgoingRequestFromRelationshipCreationChange auf CreateAndCompleteRequestFromRelationshipCreationChange abändern?

Joa, können wir gerne machen.

2022-05-06 05:40 UTC, tnotheis commented on src/useCases/consumption/requests/CanCreateOutgoingRequest.ts
> +            // @ts-expect-error // TODO: TIMO: remove this as soon as the Type Definitions are correct
Das ist das Thema, das ich schon seit ein paar Wochen ansprechen wollte. Hier beschwert sich nach wie vor TypeScript. Können wir gerne nächste Woche mal besprechen. Setz mir am besten einen Termin rein, sonst geht es garantiert wieder unter.
Den Kommentar würde ich drinlassen (nur das "Timo" mache ich raus - ich wollte, dass es beim Review auf jeden Fall auffällt, damit ich es nicht vergesse. Aber jetzt braucht Julian die Use Cases für den Connector, weshalb ich es erstmal so merge.

2022-05-06 05:40 UTC, tnotheis commented on src/useCases/consumption/requests/CompleteIncomingRequest.ts
> +        if (consumptionRequest.status === ConsumptionRequestStatus.Completed) {
Eigentlich... nicht. ;) Keine Ahnung was ich mir dabei gedacht hab.

2022-05-06 05:40 UTC, tnotheis commented on src/useCases/consumption/requests/GetIncomingRequest.ts
> +export class GetIncomingRequestUseCase extends UseCase<GetIncomingRequestRequest, ConsumptionRequestDTO> {
Also erstmal glaube ich, dass du eh immer weißt, ob der Request, den du hast, incoming oder outgoing ist. Und dann müsste die Implementierung für ein "generisches" get so aussehen, dass ich erst `getIncomingRequest(id)` aufrufe, und wenn das Ergebnis undefined ist, danach noch `getOutgoingRequest(id)`.

2022-05-06 05:40 UTC, tnotheis commented on src/extensibility/facades/consumption/OutgoingRequestsFacade.ts
> -
@jkoenig134 Der Code war absichtlich noch drin... Das war unser Versuch, den Input der from-Methode zu verbessern.

Gut dass ich das noch gesehen habe. Durch den Squash verschwindet das ja.

2022-05-06 05:58 UTC, stnmtz commented on src/useCases/consumption/requests/CanCreateOutgoingRequest.ts
> +            // @ts-expect-error // TODO: TIMO: remove this as soon as the Type Definitions are correct
Wenn das nur TS ist, würde ich das auf nach V2 schieben.

2022-05-06 06:16 UTC, jkoenig134 commented on src/useCases/consumption/requests/CanCreateOutgoingRequest.ts
> +            // @ts-expect-error // TODO: TIMO: remove this as soon as the Type Definitions are correct
@stnmtz wenn ein @ts-expect-error invalide ist ist das sogar ein Compilerfehler

2022-05-06 08:04 UTC, jkoenig134 approved these changes

2022-05-06 08:05 UTC, stnmtz approved these changes

2022-05-06 08:35 UTC, jkoenig134 approved these changes

2022-05-06 08:35 UTC, merged