Feat/files schema validation
nmshd/cns-runtime pull request #8
Opened 2021-11-10 09:41 UTC by smelm

Replaces fluent-ts-validator for most file requests. This is achieved with a combination of [ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator) and [ajv](https://ajv.js.org/).

The most significant additions are `SchemaRepository` and `SchemaValidator`.

During startup there is a performance hit that is caused by `ts-json-schema-generator` which does not respect the path to the request files and instead parses the entire project. If there is no easy fix for this it can be avoided be looping through the requests ourselves.

2021-11-10 09:58 UTC, smelm commented on src/useCases/common/SchemaRepository.ts
> +];
These should probably be moved to a different file. Where would it make sense?

2021-11-10 13:56 UTC, smelm commented on src/useCases/common/SchemaRepository.ts
> +};
These should probably be moved to a different file. Where would it make sense?

2021-11-12 08:15 UTC, jkoenig134 approved these changes

2021-11-12 13:22 UTC, jkoenig134 requested changes

2021-11-12 13:22 UTC, jkoenig134 commented on .gitignore
> +*.log
newline

2021-11-12 13:22 UTC, jkoenig134 commented on .prettierignore
> +src/useCases/common/Schemas.ts
newline

2021-11-12 13:22 UTC, jkoenig134 commented on src/useCases/transport/files/DownloadFile.ts
> +class Validator extends SchemaValidator<DownloadFileRequest> {
Validator ist an der falschen stelle

2021-11-12 13:22 UTC, jkoenig134 commented on src/useCases/transport/files/DownloadFile.ts
> +class Validator extends SchemaValidator<DownloadFileRequest> {
(sollte schon einheitlich sein)

2021-11-12 13:41 UTC, jkoenig134 approved these changes

2021-11-12 13:46 UTC, merged